# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}      
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: ballerina-platform/setup-ballerina@v1
        name: Install Ballerina
        with:
          version: 2201.12.9

      - name: Build users auth
        run: cd ./auth && bal build --cloud="docker"

      - name: Push auth
        run: docker push felipedb91/ignitegym-api-auth:v0.0.1
          
      - name: Build users exercises
        run: cd ./exercises && bal build --cloud="docker"

      - name: Push exercises
        run: docker push felipedb91/ignitegym-api-exercises:v0.0.1

      - name: Build users groups
        run: cd ./groups && bal build --cloud="docker"

      - name: Push groups
        run: docker push felipedb91/ignitegym-api-groups:v0.0.1

      - name: Build users histories
        run: cd ./histories && bal build --cloud="docker"

      - name: Push histories
        run: docker push elipedb91/ignitegym-api-histories:v0.0.1

      - name: Build users users
        run: cd ./users && bal build --cloud="docker"

      - name: Push users
        run: docker push felipedb91/ignitegym-api-users:v0.0.1
          
